### ISSUE TITLE
Jump to template

### ISSUE THREAD

**Issue by Real-Gecko** [devmahdi404/code-django#2]
https://marketplace.visualstudio.com/items?itemName=batisteo.vscode-django has some neat feature:
```
Go to definition in templates

Ctrl-click or press F12 on the template path in a include or extends tag to jump to this template
```
Can this feature be added to this extension also?

**Comment by residentcode** [comment]
Is it possible to add color to {{  }} {% %} please? I can hardly see them in code .
Great job.

**Comment by devmahdi404** [comment]
Coming soon 

![ezgif-5-b9ff965e98](https://user-images.githubusercontent.com/68297852/171917038-dff2af31-d28b-43f6-a9f2-2a0ba98f8bfd.gif)

Support this project guys, if you can. cheers 🍻

**Comment by devmahdi404** [comment]
Clesed by 50aaec33b603630cf0d54231e8d995d1cb0d4833
