### ISSUE TITLE
Using comments with VS Code shorcuts?

### ISSUE THREAD

**Issue by ddahan** [devmahdi404/code-django#6]
In the extension presentation, I can read:

> Zero config , No need to switch to django-html !

However, how auto-comment feature in VS Code is supposed to work , this way?

For example, when I want to comment this block, here is what happens:

<img width="585" alt="image" src="https://user-images.githubusercontent.com/1933516/178240338-9d099225-000c-42ca-b26a-7ad8fb4238f2.png">

Of course, I would expect Django template comments like `{# ... #}` to be used. I don't have this issue with [other extension](https://marketplace.visualstudio.com/items?itemName=batisteo.vscode-django) in which `django-html` format is used rather than normal HTML for Django templates.

Thanks for your help.

**Comment by devmahdi404** [comment]
I think `ctrl+/` should be left for html commenting (`<!-- -->`)

I am setting `ctrl+shift+/` for Django commenting. But currently, it will only support single-line comments (`{# #}`).
For multiline comments, you can use the `comment_block` snippet. To do so, select the block you want to comment, type `comment_block` then hit `tab`.

Using another language(`django-html`) disables many vscode `html` and embedded `css`, `js` features. Where you have to create a language server for that language and forward requests to the respective language servers of the embedded languages. Which requires a lot of work and that **other extensions** don't have. But have a lot of other issues.

Don't forget to support the project if you can.

**Comment by devmahdi404** [comment]
Closed by (7a6a48590d995d7dc9674c4886c253a79ce8e015)

**Comment by ddahan** [comment]
> I am setting ctrl+shift+/ for Django commenting. But currently, it will only support single-line comments (`{# #}`)

I'm not sure how am I supposed to setup this. For example in VS Code, while I know how to configure the shortcuts to toggle comments, where am I supposed to tell: "to comment this block, please use `{# ... #}`" characters?
Since it's an HTML file, VS Code will always use `<!-- ... -->` when commenting.

> For multiline comments, you can use the comment_block snippet

Please note that using `{% comment %}` block does not grayed out the commented text. I think this is a bug:

<img width="586" alt="image" src="https://user-images.githubusercontent.com/1933516/178456176-b253290f-ef10-4826-a8ab-ebeca8f1af98.png">

In addition, it seems that using this method, there is no way to uncomment a commented block.

> I think ctrl+/ should be left for html commenting ()

As a personal opinion, I'd prefer using the same shortcut to comment every filetype, with my IDE intelligent enough to pick the right characters. But I understand if it's complicated. 

> Don't forget to support the project if you can

I'll be glad to sponsor the project if my problems can be solved in a clean way. As you said, extensions using another language (`django-html`) have many issues. That's why I had hope using yours. However, commenting is very important as it is constantly used by developers, and I won't be able to use this extension without proper way to do it.

Thanks!

**Comment by devmahdi404** [comment]
> I'm not sure how am I supposed to setup this. For example in VS Code, while I know how to configure the shortcuts to toggle comments, where am I supposed to tell: "to comment this block, please use `{# ... #}`" characters? Since it's an HTML file, VS Code will always use `<!-- ... -->` when commenting.

I have added single-line comment feature in the `0.4.0` release.
Now you can find it in the [features ](https://github.com/devmahdi404/code-django#features) section.

> Please note that using `{% comment %}` block does not grayed out the commented text. I think this is a bug:
> 
> <img alt="image" width="586" src="https://user-images.githubusercontent.com/1933516/178456176-b253290f-ef10-4826-a8ab-ebeca8f1af98.png">
> 

It's not greyed out [Django documentation](https://docs.djangoproject.com/en/4.0/ref/templates/builtins/#comment).

> In addition, it seems that using this method, there is no way to uncomment a commented block.

It requires document indent info, which VSCode does not provide currently. I have opened [this](https://github.com/microsoft/vscode/issues/154896) issue for that.

> As a personal opinion, I'd prefer using the same shortcut to comment every filetype, with my IDE intelligent enough to pick the right characters. But I understand if it's complicated.

It is impossible. Leave `ctrl+/` for html commenting and use `ctrl+shift+/` for django commenting.


> I'll be glad to sponsor the project if my problems can be solved in a clean way. As you said, extensions using another language (`django-html`) have many issues. That's why I had hope using yours. However, commenting is very important as it is constantly used by developers, and I won't be able to use this extension without proper way to do it.
> 
> Thanks!

Hope you have your answers now.

**Comment by ddahan** [comment]
Great, I'll patiently watch the new releases then. Thanks for the good work.

**Comment by devmahdi404** [comment]
check the `0.5.0` release. Hope everything is fine.
